### ISSUE TITLE
Bug d'installation

### ISSUE THREAD

**Issue by moiy** [Litarvan/S-Update-Server#10]
Bonjour je voudrais utiliser S-Update, malheureusement sur la dernière version dans la console il me met une erreur qu'il n'arrive pas a se connecter (Le file explorer n'existe plus ?) et sur d'autre version du serveur il me redirige vers la page login qui n'existe pas.

**Comment by Litarvan** [comment]
Oui le FileExplorer n'éxiste plus, et il me faut l'erreur, et surtout vérifie que tu ais bien la 3.1.0 des deux côtés. Sinon c'est peut être que tu n'as pas mod_rewrite à ce moment là va sur /index.php/ avec le / a la fin, et côté code après new SUpdate(......); Rajoute su.getServerRequester().setRewriteEnabled(true);

**Comment by moiy** [comment]
ok je teste au plus vite. Merci

**Comment by moiy** [comment]
Merci ça fonctionne !
