### ISSUE TITLE
Suggestion: adding an NGINX configuration (Ajout d'une configuration NGINX)

### ISSUE THREAD

**Issue by sam543381** [Litarvan/S-Update-Server#12]
# EN
Hello,
I'm currently working on a server who handle more than 100 requests per second during highly active hours and we are having some performances issues with apache2. Htaccess files in the project force us to use apache2 instead of NGINX which is a more performant and recent web/tcp server/proxy. This issue aims to suggest you to add an NGINX configuration to make this project deployable on systems handling bigger loads.

Best,
Samuel

# FR
Bonjour,
Je travaille actuellement cher PaladiumPVP qui reçoit un peu plus d'une centaine de requêtes par secondes en utilisant S-Update, nous avons pu constater de gros problèmes de performances. Les htaccess présents dans le projet ne permettent pas de déployer S-Update-Server sur NGINX de manière sécurisée c'est pourquoi je me permets de rédiger cette issue pour vous suggérer de rendre le projet compatible pour permettre son déploiement sur ce logiciel plus sur et performant qui se veut largement utilisé.

Bien à vous,
Samuel.

**Comment by Litarvan** [comment]
Bonsoir, c'est déployable sur NGINX, tu supprimes le .htaccess et d'après la doc de mon framework la config NGINX doit ressembler à ça : 

```nginx
server {
    server_name domain.tld www.domain.tld;
    root /var/www/project/web;

    location / {
        # try to serve file directly, fallback to front controller
        try_files $uri /index.php$is_args$args;
    }

    # If you have 2 front controllers for dev|prod use the following line instead
    # location ~ ^/(index|index_dev)\.php(/|$) {
    location ~ ^/index\.php(/|$) {
        # the ubuntu default
        fastcgi_pass   unix:/var/run/php/phpX.X-fpm.sock;
        # for running on centos
        #fastcgi_pass   unix:/var/run/php-fpm/www.sock;

        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;

        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/index.php/some-path
        # Enable the internal directive to disable URIs like this
        # internal;
    }

    #return 404 for all php files as we do have a front controller
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
```

Je ne sais pas du tout utiliser NGINX donc je sais pas comment configurer ça, mais appart ça, c'est compatible.
