### ISSUE TITLE
Can't install | Installation impossible

### ISSUE THREAD

**Issue by sam543381** [Litarvan/S-Update-Server#7]
Hello. I tried to install this framework with the latest version of S-Update (client).
The installation begin and I have a page asking the admin password. If I enter two identical passwords and submit the form, the page is just reloaded.I really would like to update my launcher to fix bugs.
I'm on an Apache server (more informations in http headers).

Bonjour. J'ai essayé d'installer la dernière version de S-Update côté serveur. L'installation a correctement commencée, j'ai essayé de rentrer un mot de passe admin mais en complétant correctement le formulaire, l'envoyer ne fait que recharger la page. Il est très important pour moi de mettre à jour mon client (launcher).
PS: Je suis sous apache (cf. en-tête http).

Installation folder : http://ts.paladium-pvp.fr/update/

**Comment by Litarvan** [comment]
Il suffit de mettre les permissions 777 sur tout le dossier (recursive)
