### ISSUE TITLE
[BUG] - Liste de petit bug

### ISSUE THREAD

**Issue by Misteralex007** [Litarvan/S-Update-Server#9]
Bonsoir,

Voici une petite liste de bug:

Dans settings:
->Le deuxième champ pour le mot de passe est en clair.
Est-ce voulu ?
-> On ne peut plus choisir sa langue ?
Est-ce normal .

Dans home:
->Panneau de contrôle disparu malgré la création du dossier Files

Dans statistics:
-> Le bouton "Home" ne fonctionne pas
Alors que celui dans about fonctionne.

Voilà c'est tout ce que j'ai remarqué.
Est-ce un problème avec mon navigateur internet ?

Merci d'avance.
Misteralex007

**Comment by Litarvan** [comment]
Pour le deuxième champ de mot de passe merci je corrige ça.
Pour la langue c'est voulu car j'ai du refaire la base et ça ne servait pas à grand chose.
Le panneau de contrôle c'est ce sur quoi tu es, je n'ai juste pas eu le temps de refaire le File Explorer quand j'ai refais la base.
Le bouton home fonctionne chez moi mais ça va changer de toute façon.

Bref tout ça sera réglé / remis dans la 3.2 sur laquelle je bosse en te parlant.

**Comment by Misteralex007** [comment]
D'accord très bien.
Juste comme ça, elle sera disponible bientôt ?

**Comment by Litarvan** [comment]
Oui

**Comment by Misteralex007** [comment]
D'accord.
Mais elle fonctionne cela fonctionne quand même.
Si je créé moi même mon répertoire files et que je mets les fichiers dedans et après dans le launcher j'indique la bonne adresse cela est censé fonctionner ?

**Comment by Litarvan** [comment]
Bien sur
